#!/usr/bin/env bash
exec docker run \
	-it \
	--net host \
	--ipc host \
	--gpus all \
	-e DISPLAY \
	-v "$XAUTHORITY:/root/.Xauthority:ro" \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v "$PWD:/host" \
	--name "ros-humble" \
	my-ros "$@"
