#!/usr/bin/env bash
exec docker run \
	-it \
	--net=host \
	--device /dev/dri/ \
	-e DISPLAY="$DISPLAY" \
	-v "$HOME/.Xauthority:/root/.Xauthority:ro" \
	-v "$PWD:/host" \
	--name "ros-humble" \
	my-ros "$@"
